interface TranslationsInterface {
  language: string,
  getInvolvedTitle: string,
  getInvolvedStrapline: string,
  progressTitle: string,
  progressStrapline: string,
  joinCardOneTitle: string,
  joinCardTwoTitle: string,
  joinCardThreeTitle: string,
  progressCardOneTitle: string,
  progressCardTwoTitle: string,
  progressCardThreeTitle: string,
  joinCardOneIntro: string,
  joinCardTwoIntro: string,
  joinCardThreeIntro: string,
  progressCardOneIntro: string,
  progressCardTwoIntro: string,
  progressCardThreeIntro: string,

}

const HomeCopy: { [key: string]: TranslationsInterface; } = {
  cn: {
    language: '中文',
    getInvolvedTitle: 'Get involved',
    getInvolvedStrapline: 'eliminating the confusion around blockchain',
    progressTitle: 'Progress',
    progressStrapline: 'progress lies not in enhancing what is, but in advancing toward what will be',
    joinCardOneTitle: 'Launch On Worbli',
    joinCardTwoTitle: 'Partner With Us',
    joinCardThreeTitle: 'Open An Account',
    progressCardOneTitle: 'Worbli partners with wordproof',
    progressCardTwoTitle: 'Every month new partners launch',
    progressCardThreeTitle: 'Chain updates and new protocols',
    joinCardOneIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    joinCardTwoIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    joinCardThreeIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    progressCardOneIntro: 'Browse WORBLI related articles and news',
    progressCardTwoIntro: 'Keep up to date with the new and exciting applications launching on WORBLI',
    progressCardThreeIntro: 'View our proposed and past technical updates and current chain specifications',
  },
  kr: {
    language: '한국어',
    getInvolvedTitle: 'Get involved',
    getInvolvedStrapline: 'eliminating the confusion around blockchain',
    progressTitle: 'Progress',
    progressStrapline: 'progress lies not in enhancing what is, but in advancing toward what will be',
    joinCardOneTitle: 'Launch On Worbli',
    joinCardTwoTitle: 'Partner With Us',
    joinCardThreeTitle: 'Open An Account',
    progressCardOneTitle: 'Worbli partners with wordproof',
    progressCardTwoTitle: 'Every month new partners launch',
    progressCardThreeTitle: 'Chain updates and new protocols',
    joinCardOneIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    joinCardTwoIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    joinCardThreeIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    progressCardOneIntro: 'Browse WORBLI related articles and news',
    progressCardTwoIntro: 'Keep up to date with the new and exciting applications launching on WORBLI',
    progressCardThreeIntro: 'View our proposed and past technical updates and current chain specifications',
  },
  en: {
    language: 'English',
    getInvolvedTitle: 'Get involved',
    getInvolvedStrapline: 'Help us build a fair and inclusive world through enterprise-grade financial technology.',
    progressTitle: 'Progress',
    progressStrapline: "progress lies not in enhancing what is, but in advancing toward what will be",
    joinCardOneTitle: 'Launch On Worbli',
    joinCardTwoTitle: 'Partner With Us',
    joinCardThreeTitle: 'Open An Account',
    progressCardOneTitle: 'Worbli partners with wordproof',
    progressCardTwoTitle: 'Every month new partners launch',
    progressCardThreeTitle: 'Chain updates and new protocols',
    joinCardOneIntro: 'Are you working on a blockchain application that needs to be compliant with global laws and regulations? If so, WORBLI may be the right choice for you.',
    joinCardTwoIntro: 'The WORBLI ecosystem is about cooperation. If you can provide a core service to the network, such as identity verification, dispute resolution or developer integrations, we’d love to hear from you.',
    joinCardThreeIntro: 'Join the financial revolution by creating your WORBLI account. Get verified once and gain access to all WORBLI-powered financial services.  With an identity based recoverable account on WORBLI you can interact with the newest DeFi applications with a single authorization.  The account application process is quick, easy and free.',
    progressCardOneIntro: 'Browse WORBLI related articles and news',
    progressCardTwoIntro: 'Keep up to date with the new and exciting applications launching on WORBLI',
    progressCardThreeIntro: 'View our proposed and past technical updates and current chain specifications',
  },
}
export { HomeCopy }
