interface TranslationsInterface {
  language: string,
  getInvolvedTitle: string,
  getInvolvedStrapline: string,
  progressTitle: string,
  progressStrapline: string,
  joinCardOneTitle: string,
  joinCardTwoTitle: string,
  joinCardThreeTitle: string,
  progressCardOneTitle: string,
  progressCardTwoTitle: string,
  progressCardThreeTitle: string,
  joinCardOneIntro: string,
  joinCardTwoIntro: string,
  joinCardThreeIntro: string,
  progressCardOneIntro: string,
  progressCardTwoIntro: string,
  progressCardThreeIntro: string,

}

const HomeCopy: { [key: string]: TranslationsInterface; } = {
  cn: {
    language: '中文',
    getInvolvedTitle: 'Get involved',
    getInvolvedStrapline: 'eliminating the confusion around blockchain',
    progressTitle: 'Progress',
    progressStrapline: 'progress lies not in enhancing what is, but in advancing toward what will be.',
    joinCardOneTitle: 'Launch On Worbli',
    joinCardTwoTitle: 'Partner With Us',
    joinCardThreeTitle: 'Open An Account',
    progressCardOneTitle: 'Worbli partners with wordproof',
    progressCardTwoTitle: 'Every month new partners launch',
    progressCardThreeTitle: 'Chain updates and new protocols',
    joinCardOneIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    joinCardTwoIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    joinCardThreeIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    progressCardOneIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet',
    progressCardTwoIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet',
    progressCardThreeIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet',
  },
  kr: {
    language: '한국어',
    getInvolvedTitle: 'Get involved',
    getInvolvedStrapline: 'eliminating the confusion around blockchain',
    progressTitle: 'Progress',
    progressStrapline: 'progress lies not in enhancing what is, but in advancing toward what will be.',
    joinCardOneTitle: 'Launch On Worbli',
    joinCardTwoTitle: 'Partner With Us',
    joinCardThreeTitle: 'Open An Account',
    progressCardOneTitle: 'Worbli partners with wordproof',
    progressCardTwoTitle: 'Every month new partners launch',
    progressCardThreeTitle: 'Chain updates and new protocols',
    joinCardOneIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    joinCardTwoIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    joinCardThreeIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    progressCardOneIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet',
    progressCardTwoIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet',
    progressCardThreeIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet',
  },
  en: {
    language: 'English',
    getInvolvedTitle: 'Get involved',
    getInvolvedStrapline: 'eliminating the confusion around blockchain',
    progressTitle: 'Progress',
    progressStrapline: 'progress lies not in enhancing what is, but in advancing toward what will be.',
    joinCardOneTitle: 'Launch On Worbli',
    joinCardTwoTitle: 'Partner With Us',
    joinCardThreeTitle: 'Open An Account',
    progressCardOneTitle: 'Worbli partners with wordproof',
    progressCardTwoTitle: 'Every month new partners launch',
    progressCardThreeTitle: 'Chain updates and new protocols',
    joinCardOneIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    joinCardTwoIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    joinCardThreeIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet sit amet tempor mollis, sollicitudin nec velit. Nunc condimentum tempus felis, vel tincidunt libero viverra vitae. In pellentesque eget metus sit amet tincidunt. Nullam sollicitudin urna quis dolor convallis ullamcorper. Pellentesque at sodales lectus. Nullam dolor velit, accumsan consequat ipsum in, blandit elementum massa.',
    progressCardOneIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet',
    progressCardTwoIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet',
    progressCardThreeIntro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quam massa, laoreet',
  },
}
export { HomeCopy }
